Train loader batch shapes:
Traceback (most recent call last):
  File "/home/mateo/projects/ai/indiofinder/train.py", line 283, in <module>
    main()
  File "/home/mateo/projects/ai/indiofinder/train.py", line 148, in main
    data_loader = DataLoaderPyTorch(train_file, test_file, batch_size=batch_size, num_workers=num_workers)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mateo/projects/ai/indiofinder/dataloader.py", line 76, in __init__
    prefetch_factor=2,
  File "/home/mateo/projects/ai/indiofinder/dataloader.py", line 101, in _prepare_data
    break
  File "/home/mateo/projects/ai/indiofinder/dataloader.py", line 105, in _verify_batch_shapes
  File "/home/mateo/projects/ai/indiofinder/env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/mateo/projects/ai/indiofinder/env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1327, in _next_data
    idx, data = self._get_data()
                ^^^^^^^^^^^^^^^^
  File "/home/mateo/projects/ai/indiofinder/env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1283, in _get_data
    success, data = self._try_get_data()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/mateo/projects/ai/indiofinder/env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1131, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
